name: NanamiMapSystem
version: '${version}'
main: xyz.n7mn.dev.nanamimapsystem.NanamiMapSystem
load: STARTUP
authors: [ 7mi_chan ]
description: NanamiMapSystem
commands:
  create:
    description: ''
    permission-message: ''
    permission: 'nanamimap.create'