name: NanamiMapSystem
version: '${version}'
main: xyz.n7mn.dev.nanamimapsystem.NanamiMapSystem
load: STARTUP
authors: [ 7mi_chan ]
description: NanamiMapSystem
depend: [ ProtocolLib ]
commands:
  create:
    description: ''
    permission-message: ''
    permission: 'nanamimap.create'
    usage: '/create'
  delete:
    description: ''
    permission: 'nanamimap.delete'
    permission-message: ''
    usage: '/delete'
  load:
    description: ''
    permission: 'nanamimap.load'
    permission-message: ''
    usage: '/load'
  move:
    description: ''
    permission: 'nanamimap.move'
    permission-message: ''
    usage: '/move'